### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Task-BeLike-DAGOLDEN#1]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives.

(that was a stock message -- I know you are aware of this issue, but a ticket helps remember it) ;)

**Comment by dagolden** [comment]
Yeah, but I have half a dozen private scripts that use it, so until I fix
_those_, this ticket will have to stay open.  :-)

**Comment by karenetheridge** [comment]
how are those private scripts doing? I heard that Path::Tiny is pretty cool; you should check it out!

**Comment by xdg** [comment]
Scripts are cleaned up.

**Comment by xdg** [comment]
Shipped.
